export const NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_ERROR = "NEWS_LIST_ERROR";

export const NEWS_ITEM_REQUEST = "NEWS_ITEM_REQUEST";
export const NEWS_ITEM_SUCCESS = "NEWS_ITEM_SUCCESS";
export const NEWS_ITEM_ERROR = "NEWS_ITEM_ERROR";